// <auto-generated by tools/extract-static-routes.ps1 - do not edit by hand>
// Stateless endpoints: Rust handler used static_response and never touched
// UserRepository. Stateful endpoints are handled in cycles 3 and 4.
// MISSING lines are routes classified stateless whose ReqPacket_/ResPacket_ pair
// does not exist under /packets (route name and client packet name have drifted).
// Do not invent the type; these are cycle 3 items. Re-running the generator
// reproduces the same comment-outs.
using Microsoft.AspNetCore.Routing;

public static class StaticRoutes
{
    public static IEndpointRouteBuilder MapStaticPackets(this IEndpointRouteBuilder app)
    {
        app.MapPacket<ReqPacket_AcceptReceivedFriendRequest, ResPacket_AcceptReceivedFriendRequest>("/api/AcceptReceivedFriendRequest");
        app.MapPacket<ReqPacket_AcquireAttendanceReward, ResPacket_AcquireAttendanceReward>("/api/AcquireAttendanceReward");
        app.MapPacket<ReqPacket_AcquireDailyLoginReward, ResPacket_AcquireDailyLoginReward>("/api/AcquireDailyLoginReward");
        app.MapPacket<ReqPacket_AcquireHellsChickenReward, ResPacket_AcquireHellsChickenReward>("/api/AcquireHellsChickenReward");
        app.MapPacket<ReqPacket_AcquireMissionRewards, ResPacket_AcquireMissionRewards>("/api/AcquireMissionRewards");
        app.MapPacket<ReqPacket_AcquireRailwayDungeonReward, ResPacket_AcquireRailwayDungeonReward>("/api/AcquireRailwayDungeonReward");
        app.MapPacket<ReqPacket_BattlePassExLevelReward, ResPacket_BattlePassExLevelReward>("/api/BattlePassExLevelReward");
        app.MapPacket<ReqPacket_BattlePassMissionReward, ResPacket_BattlePassMissionReward>("/api/BattlePassMissionReward");
        app.MapPacket<ReqPacket_BattlePassMissionRewardAll, ResPacket_BattlePassMissionRewardAll>("/api/BattlePassMissionRewardAll");
        app.MapPacket<ReqPacket_BattlePassReward, ResPacket_BattlePassReward>("/api/BattlePassReward");
        app.MapPacket<ReqPacket_CancelSecession, ResPacket_CancelSecession>("/login/CancelSecession");
        app.MapPacket<ReqPacket_CancelSentFriendRequest, ResPacket_CancelSentFriendRequest>("/api/CancelSentFriendRequest");
        app.MapPacket<ReqPacket_CheckClientVersion, ResPacket_CheckClientVersion>("/login/CheckClientVersion");
        app.MapPacket<ReqPacket_CheckSeasonLog, ResPacket_CheckSeasonLog>("/api/CheckSeasonLog");
        app.MapPacket<ReqPacket_ClaimClosedGachaRewards, ResPacket_ClaimClosedGachaRewards>("/api/ClaimClosedGachaRewards");
        app.MapPacket<ReqPacket_ClaimEventReward, ResPacket_ClaimEventReward>("/api/ClaimEventReward");
        app.MapPacket<ReqPacket_ClaimEventReward_ALL, ResPacket_ClaimEventReward_ALL>("/api/ClaimEventReward_ALL");
        app.MapPacket<ReqPacket_CompleteMinistory, ResPacket_CompleteMinistory>("/api/CompleteMinistory");
        app.MapPacket<ReqPacket_CompleteTheaterStory, ResPacket_CompleteTheaterStory>("/api/CompleteTheaterStory");
        app.MapPacket<ReqPacket_ConfirmedSeasonLog, ResPacket_ConfirmedSeasonLog>("/api/ConfirmedSeasonLog");
        app.MapPacket<ReqPacket_DeleteFriend, ResPacket_DeleteFriend>("/api/DeleteFriend");
        app.MapPacket<ReqPacket_EgoGacksungWithItems, ResPacket_EgoGacksungWithItems>("/api/EgoGacksungWithItems");
        app.MapPacket<ReqPacket_EnableSpecialStartBuffMirrorDungeon, ResPacket_EnableSpecialStartBuffMirrorDungeon>("/api/EnableSpecialStartBuffMirrorDungeon");
        app.MapPacket<ReqPacket_EnableStartBuffMirrorDungeon, ResPacket_EnableStartBuffMirrorDungeon>("/api/EnableStartBuffMirrorDungeon");
        app.MapPacket<ReqPacket_EnterExpDungeon, ResPacket_EnterExpDungeon>("/api/EnterExpDungeon");
        app.MapPacket<ReqPacket_EnterStageBattle, ResPacket_EnterStageBattle>("/api/EnterStageBattle");
        app.MapPacket<ReqPacket_EnterStoryMirrorDungeonMapNodeBattleAfterChoice, ResPacket_EnterStoryMirrorDungeonMapNodeBattleAfterChoice>("/api/EnterStoryMirrorDungeonMapNodeBattleAfterChoice");
        app.MapPacket<ReqPacket_EnterThreadDungeon, ResPacket_EnterThreadDungeon>("/api/EnterThreadDungeon");
        app.MapPacket<ReqPacket_ExchangeTwine, ResPacket_ExchangeTwine>("/api/ExchangeTwine");
        app.MapPacket<ReqPacket_ExitExpDungeon, ResPacket_ExitExpDungeon>("/api/ExitExpDungeon");
        app.MapPacket<ReqPacket_ExitMirrorDungeon, ResPacket_ExitMirrorDungeon>("/api/ExitMirrorDungeon");
        app.MapPacket<ReqPacket_ExitStoryMirrorDungeon, ResPacket_ExitStoryMirrorDungeon>("/api/ExitStoryMirrorDungeon");
        app.MapPacket<ReqPacket_ExitThreadDungeon, ResPacket_ExitThreadDungeon>("/api/ExitThreadDungeon");
        app.MapPacket<ReqPacket_FindFriend, ResPacket_FindFriend>("/api/FindFriend");
        app.MapPacket<ReqPacket_GetAbnormalityLogData, ResPacket_GetAbnormalityLogData>("/api/GetAbnormalityLogData");
        app.MapPacket<ReqPacket_GetAttendanceState, ResPacket_GetAttendanceState>("/api/GetAttendanceState");
        app.MapPacket<ReqPacket_GetBanDetails, ResPacket_GetBanDetails>("/login/GetBanDetails");
        app.MapPacket<ReqPacket_GetDailyDungeonInfo, ResPacket_GetDailyDungeonInfo>("/api/GetDailyDungeonInfo");
        app.MapPacket<ReqPacket_GetDailyLoginState, ResPacket_GetDailyLoginState>("/api/GetDailyLoginState");
        app.MapPacket<ReqPacket_GetDanteNoteState, ResPacket_GetDanteNoteState>("/api/GetDanteNoteState");
        app.MapPacket<ReqPacket_GetFriendSupportPersonalities, ResPacket_GetFriendSupportPersonalities>("/api/GetFriendSupportPersonalities");
        app.MapPacket<ReqPacket_GetFriendSupportPersonalitiesByCharacterId, ResPacket_GetFriendSupportPersonalitiesByCharacterId>("/api/GetFriendSupportPersonalitiesByCharacterId");
        app.MapPacket<ReqPacket_GetHellsChickenState, ResPacket_GetHellsChickenState>("/api/GetHellsChickenState");
        app.MapPacket<ReqPacket_GetInfoOfLinkWith, ResPacket_GetInfoOfLinkWith>("/login/GetInfoOfLinkWith");
        app.MapPacket<ReqPacket_GetMirrorDungeonEgoGiftRecord, ResPacket_GetMirrorDungeonEgoGiftRecord>("/api/GetMirrorDungeonEgoGiftRecord");
        app.MapPacket<ReqPacket_GetProfileTicketDecoDatas, ResPacket_GetProfileTicketDecoDatas>("/api/GetProfileTicketDecoDatas");
        app.MapPacket<ReqPacket_GetRecommendFriends, ResPacket_GetRecommendFriends>("/api/GetRecommendFriends");
        app.MapPacket<ReqPacket_GetStageProgressRateReward, ResPacket_GetStageProgressRateReward>("/api/GetStageProgressRateReward");
        app.MapPacket<ReqPacket_GetStartBuffFInfoMirrorDungeon, ResPacket_GetStartBuffFInfoMirrorDungeon>("/api/GetStartBuffFInfoMirrorDungeon");
        app.MapPacket<ReqPacket_GetStoryDungeonSaveInfo, ResPacket_GetStoryDungeonSaveInfo>("/api/GetStoryDungeonSaveInfo");
        app.MapPacket<ReqPacket_GetTheaterInfo, ResPacket_GetTheaterInfo>("/api/GetTheaterInfo");
        app.MapPacket<ReqPacket_GetUserBanners, ResPacket_GetUserBanners>("/api/GetUserBanners");
        app.MapPacket<ReqPacket_GiveUpRailwayDungeonNode, ResPacket_GiveUpRailwayDungeonNode>("/api/GiveUpRailwayDungeonNode");
        app.MapPacket<ReqPacket_GiveUpRailwayDungeonNodeInBattle, ResPacket_GiveUpRailwayDungeonNodeInBattle>("/api/GiveUpRailwayDungeonNodeInBattle");
        app.MapPacket<ReqPacket_LinkWithAnother, ResPacket_LinkWithAnother>("/login/LinkWithAnother");
        app.MapPacket<ReqPacket_LinkWithApple, ResPacket_LinkWithApple>("/login/LinkWithApple");
        app.MapPacket<ReqPacket_LinkWithGoogle, ResPacket_LinkWithGoogle>("/login/LinkWithGoogle");
        app.MapPacket<ReqPacket_PersonalityGacksungWithItems, ResPacket_PersonalityGacksungWithItems>("/api/PersonalityGacksungWithItems");
        app.MapPacket<ReqPacket_PlayGacha, ResPacket_PlayGacha>("/api/PlayGacha");
        app.MapPacket<ReqPacket_PlayVendingMachine, ResPacket_PlayVendingMachine>("/api/PlayVendingMachine");
        app.MapPacket<ReqPacket_PreviewMirrorDungeonExitReward, ResPacket_PreviewMirrorDungeonExitReward>("/api/PreviewMirrorDungeonExitReward");
        app.MapPacket<ReqPacket_PurchaseBattlePassByRealLunacy, ResPacket_PurchaseBattlePassByRealLunacy>("/api/PurchaseBattlePassByRealLunacy");
        app.MapPacket<ReqPacket_PurchaseBattlePassLevel, ResPacket_PurchaseBattlePassLevel>("/api/PurchaseBattlePassLevel");
        app.MapPacket<ReqPacket_PurchaseEnkephalin, ResPacket_PurchaseEnkephalin>("/api/PurchaseEnkephalin");
        app.MapPacket<ReqPacket_PurchaseEnkephalinModule, ResPacket_PurchaseEnkephalinModule>("/api/PurchaseEnkephalinModule");
        app.MapPacket<ReqPacket_PurchaseFormationStoryMirrorDungeon, ResPacket_PurchaseFormationStoryMirrorDungeon>("/api/PurchaseFormationStoryMirrorDungeon");
        app.MapPacket<ReqPacket_PurchaseSpecialPassProduct, ResPacket_PurchaseSpecialPassProduct>("/api/PurchaseSpecialPassProduct");
        app.MapPacket<ReqPacket_PurchaseSpecialPassProduct_IncludeLimbusPass, ResPacket_PurchaseSpecialPassProduct_IncludeLimbusPass>("/api/PurchaseSpecialPassProduct_IncludeLimbusPass");
        app.MapPacket<ReqPacket_PurchaseSpecialPassProduct_NotIncludeLimbusPass, ResPacket_PurchaseSpecialPassProduct_NotIncludeLimbusPass>("/api/PurchaseSpecialPassProduct_NotIncludeLimbusPass");
        app.MapPacket<ReqPacket_PurchaseStartBuffMirrorDungeon, ResPacket_PurchaseStartBuffMirrorDungeon>("/api/PurchaseStartBuffMirrorDungeon");
        app.MapPacket<ReqPacket_PurchaseUpgradePersonalityMirrorDungeon, ResPacket_PurchaseUpgradePersonalityMirrorDungeon>("/api/PurchaseUpgradePersonalityMirrorDungeon");
        app.MapPacket<ReqPacket_PurchaseUpgradePersonalityStoryMirrorDungeon, ResPacket_PurchaseUpgradePersonalityStoryMirrorDungeon>("/api/PurchaseUpgradePersonalityStoryMirrorDungeon");
        app.MapPacket<ReqPacket_ReEnterStoryMirrorDungeon, ResPacket_ReEnterStoryMirrorDungeon>("/api/ReEnterStoryMirrorDungeon");
        app.MapPacket<ReqPacket_RefreshLinkAuth, ResPacket_RefreshLinkAuth>("/login/RefreshLinkAuth");
        app.MapPacket<ReqPacket_RefreshMailbox, ResPacket_RefreshMailbox>("/api/RefreshMailbox");
        app.MapPacket<ReqPacket_RefreshStartEgoGiftsMirrorDungeon, ResPacket_RefreshStartEgoGiftsMirrorDungeon>("/api/RefreshStartEgoGiftsMirrorDungeon");
        app.MapPacket<ReqPacket_RefreshStartEgoGiftsStoryMirrorDungeon, ResPacket_RefreshStartEgoGiftsStoryMirrorDungeon>("/api/RefreshStartEgoGiftsStoryMirrorDungeon");
        app.MapPacket<ReqPacket_RejectReceivedFriendRequest, ResPacket_RejectReceivedFriendRequest>("/api/RejectReceivedFriendRequest");
        app.MapPacket<ReqPacket_RejectRewardEgoGiftsStoryMirrorDungeon, ResPacket_RejectRewardEgoGiftsStoryMirrorDungeon>("/api/RejectRewardEgoGiftsStoryMirrorDungeon");
        app.MapPacket<ReqPacket_RejectRewardEgoGiftWithEnemyBufsMirrorDungeon, ResPacket_RejectRewardEgoGiftWithEnemyBufsMirrorDungeon>("/api/RejectRewardEgoGiftWithEnemyBufsMirrorDungeon");
        app.MapPacket<ReqPacket_RemoveMirrorDungeonEgoGift, ResPacket_RemoveMirrorDungeonEgoGift>("/api/RemoveMirrorDungeonEgoGift");
        app.MapPacket<ReqPacket_RemoveStoryMirrorDungeonEgoGift, ResPacket_RemoveStoryMirrorDungeonEgoGift>("/api/RemoveStoryMirrorDungeonEgoGift");
        app.MapPacket<ReqPacket_ReportError, ResPacket_ReportError>("/api/ReportError");
        app.MapPacket<ReqPacket_SaveMiniStoryWeek, ResPacket_SaveMiniStoryWeek>("/api/SaveMiniStoryWeek");
        app.MapPacket<ReqPacket_SelectRailwayDungeonBuff, ResPacket_SelectRailwayDungeonBuff>("/api/SelectRailwayDungeonBuff");
        app.MapPacket<ReqPacket_SendFriendRequest, ResPacket_SendFriendRequest>("/api/SendFriendRequest");
        app.MapPacket<ReqPacket_SendMirrorDungeonLogError, ResPacket_SendMirrorDungeonLogError>("/api/SendMirrorDungeonLogError");
        app.MapPacket<ReqPacket_SendMirrorDungeonShopExit, ResPacket_SendMirrorDungeonShopExit>("/api/SendMirrorDungeonShopExit");
        app.MapPacket<ReqPacket_SetPersonalityGacksungIllust, ResPacket_SetPersonalityGacksungIllust>("/api/SetPersonalityGacksungIllust");
        app.MapPacket<ReqPacket_SignInAsApple, ResPacket_SignInAsApple>("/login/SignInAsApple");
        app.MapPacket<ReqPacket_SignInAsGoogle, ResPacket_SignInAsGoogle>("/login/SignInAsGoogle");
        app.MapPacket<ReqPacket_SignInAsGuest, ResPacket_SignInAsGuest>("/login/SignInAsGuest");
        app.MapPacket<ReqPacket_SignInAsNewGuest, ResPacket_SignInAsNewGuest>("/login/SignInAsNewGuest");
        app.MapPacket<ReqPacket_SkipExpDungeon, ResPacket_SkipExpDungeon>("/api/SkipExpDungeon");
        app.MapPacket<ReqPacket_SkipThreadDungeon, ResPacket_SkipThreadDungeon>("/api/SkipThreadDungeon");
        app.MapPacket<ReqPacket_SkipTutorial, ResPacket_SkipTutorial>("/api/SkipTutorial");
        app.MapPacket<ReqPacket_TryToSecede, ResPacket_TryToSecede>("/login/TryToSecede");
        app.MapPacket<ReqPacket_UnLinkWithAnother, ResPacket_UnLinkWithAnother>("/login/UnLinkWithAnother");
        app.MapPacket<ReqPacket_UnsealMails, ResPacket_UnsealMails>("/api/UnsealMails");
        app.MapPacket<ReqPacket_UpdateAbnormalityLogData, ResPacket_UpdateAbnormalityLogData>("/api/UpdateAbnormalityLogData");
        app.MapPacket<ReqPacket_UpdateLobbyCg, ResPacket_UpdateLobbyCg>("/api/UpdateLobbyCg");
        app.MapPacket<ReqPacket_UpdateMirrorDungeon, ResPacket_UpdateMirrorDungeon>("/api/UpdateMirrorDungeon");
        app.MapPacket<ReqPacket_UpdateMirrorDungeonUnits, ResPacket_UpdateMirrorDungeonUnits>("/api/UpdateMirrorDungeonUnits");
        app.MapPacket<ReqPacket_UpdateProfileTicketDeco, ResPacket_UpdateProfileTicketDeco>("/api/UpdateProfileTicketDeco");
        app.MapPacket<ReqPacket_UpdateStoryDungeonUnits, ResPacket_UpdateStoryDungeonUnits>("/api/UpdateStoryDungeonUnits");
        app.MapPacket<ReqPacket_UpdateStoryMirrorDungeonUnits, ResPacket_UpdateStoryMirrorDungeonUnits>("/api/UpdateStoryMirrorDungeonUnits");
        app.MapPacket<ReqPacket_UpdateTermsOfUseState, ResPacket_UpdateTermsOfUseState>("/login/UpdateTermsOfUseState");
        app.MapPacket<ReqPacket_UpdateUserProfile, ResPacket_UpdateUserProfile>("/api/UpdateUserProfile");
        app.MapPacket<ReqPacket_UseEgoGacksungItem, ResPacket_UseEgoGacksungItem>("/api/UseEgoGacksungItem");
        app.MapPacket<ReqPacket_UseGachaPityPoint, ResPacket_UseGachaPityPoint>("/api/UseGachaPityPoint");
        app.MapPacket<ReqPacket_UseItem, ResPacket_UseItem>("/api/UseItem");
        app.MapPacket<ReqPacket_UsePersonalityExpItem, ResPacket_UsePersonalityExpItem>("/api/UsePersonalityExpItem");
        // MISSING: /api/BattlePassReward_ALL - ReqPacket_BattlePassReward_ALL/ResPacket_BattlePassReward_ALL not found under /packets
        // MISSING: /api/EgoGacksung - ReqPacket_EgoGacksung/ResPacket_EgoGacksung not found under /packets
        // MISSING: /api/EnterExpDungeonv2 - ReqPacket_EnterExpDungeonv2/ResPacket_EnterExpDungeonv2 not found under /packets
        // MISSING: /api/EnterMirrordungeonMapNodeBattleAfterChoice - ReqPacket_EnterMirrordungeonMapNodeBattleAfterChoice/ResPacket_EnterMirrordungeonMapNodeBattleAfterChoice not found under /packets
        // MISSING: /api/EnterStoryDungeonMapNodeBattleAfterChoice - ReqPacket_EnterStoryDungeonMapNodeBattleAfterChoice/ResPacket_EnterStoryDungeonMapNodeBattleAfterChoice not found under /packets
        // MISSING: /api/ExitExpDungeonv2 - ReqPacket_ExitExpDungeonv2/ResPacket_ExitExpDungeonv2 not found under /packets
        // MISSING: /api/GetFriendsData - ReqPacket_GetFriendsData/ResPacket_GetFriendsData not found under /packets
        // MISSING: /api/GetStoryDungeonNodeRecord - ReqPacket_GetStoryDungeonNodeRecord/ResPacket_GetStoryDungeonNodeRecord not found under /packets
        // MISSING: /api/GetUserCouponState - ReqPacket_GetUserCouponState/ResPacket_GetUserCouponState not found under /packets
        // MISSING: /api/PersonalityGacksung - ReqPacket_PersonalityGacksung/ResPacket_PersonalityGacksung not found under /packets
        return app;
    }

    public static int RegisteredCount => 112;
}

