// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenLethe.Data;

#nullable disable

namespace OpenLethe.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819032324_IngameIdIdentity")]
    partial class IngameIdIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenLethe.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Announcers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BossRaidSaveInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ChapterState")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomEgos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomIdentities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomTheme")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<string>("Egos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Formations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("IngameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngameId"));

                    b.Property<string>("MdSaveInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Personalities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RailwaySaveInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StoryMdSaveInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StorySaveInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasFilter("\"DiscordId\" IS NOT NULL");

                    b.HasIndex("IngameId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
