# Generates StaticRoutes.cs from the Rust router plus handler classification.
# A handler is "static" iff it uses static_response and never touches UserRepository.
# Re-run when the Rust server adds endpoints; output is committed.
#
# Scope is /api/* and /login/* routes (matches the brief's regex) - the /iap
# and /log route groups use the same static_response/UserRepository idiom but
# are a separate subsystem and out of scope for this task.
#
# A classified-static route whose ReqPacket_<Name>/ResPacket_<Name> pair does
# not exist under /packets (route/client packet names have drifted) is never
# invented - it's commented out with `// MISSING:` and reported, deterministically,
# so a regen reproduces the same comment-outs instead of silently dropping them.

param(
    [string]$RustRoot = "C:\Users\Limi\Desktop\Projects\lethe-server",
    [string]$PacketsRoot = "$PSScriptRoot\..\packets",
    [string]$OutFile  = "$PSScriptRoot\..\src\OpenLethe.Server\StaticRoutes.cs"
)

$ErrorActionPreference = "Stop"

$routerText = Get-Content "$RustRoot\server\src\router.rs" -Raw

# router.route("/api/Name", post(path::to::handler_fn)) - handler may be
# wrapped across lines and/or have a trailing comma before the closing paren,
# e.g. BattlePassExLevelReward's post(\n    crate::...::handle_x,\n),
$routePattern = 'route\(\s*"(?<route>/(?:api|login)/[^"]+)"\s*,\s*post\(\s*(?<handler>[\w:]+)\s*,?\s*\)'
$routeMatches = [regex]::Matches($routerText, $routePattern)
if ($routeMatches.Count -eq 0) { throw "No routes matched - check regex against router.rs" }

# Build the set of ReqPacket_/ResPacket_ class names actually present under
# /packets, so a route/handler name that has drifted from the client packet
# name gets caught and commented out instead of failing the build with CS0246.
$packetClassNames = New-Object 'System.Collections.Generic.HashSet[string]'
Get-ChildItem -Path $PacketsRoot -Filter *.cs -Recurse | ForEach-Object {
    $text = Get-Content $_.FullName -Raw
    foreach ($cm in [regex]::Matches($text, 'class\s+((Req|Res)Packet_\w+)')) {
        $className = $cm.Groups[1].Value
        [void]$packetClassNames.Add($className)
    }
}

# Routes whose Rust handler uses static_response but with NON-DEFAULT data the
# generic MapPacket can't reproduce (it would return an empty/default result).
# These need a hand-written handler and are registered in Program.cs, not here.
$forceRealHandler = @(
    '/login/GetTermsOfUseStateAll'      # returns terms as accepted (version 1, state 1)
    '/api/GetMirrorDungeonEgoGiftRecord' # real handler: enumerates all MD ego gifts + themes
    '/api/ExitMirrorDungeon'             # real handler: returns isEndDungeon=1, isclear=1
)

$static = @()
$skipped = @()
$missing = @()

foreach ($m in $routeMatches) {
    $route   = $m.Groups['route'].Value
    $handler = $m.Groups['handler'].Value

    if ($forceRealHandler -contains $route) { $skipped += "$route (real handler required - non-default static data)"; continue }

    # crate::api::battlepass::battle_pass_reward::handle_x -> api/battlepass/battle_pass_reward.rs
    $parts = $handler -split '::'
    if ($parts.Length -lt 2) { continue }
    $moduleParts = $parts[1..($parts.Length - 2)]   # drop leading "crate" and trailing fn name
    $file = Join-Path "$RustRoot\server\src" (($moduleParts -join '\') + ".rs")

    if (-not (Test-Path $file)) {
        $file = Join-Path "$RustRoot\server\src" (($moduleParts -join '\') + "\mod.rs")
    }
    if (-not (Test-Path $file)) { $skipped += "$route (source not found: $file)"; continue }

    $body = Get-Content $file -Raw
    $isStatic = ($body -match 'static_response') -and ($body -notmatch 'UserRepository')
    if (-not $isStatic) { $skipped += "$route (stateful)"; continue }

    # /api/EnterBossRaid -> EnterBossRaid; /login/CheckClientVersion -> CheckClientVersion
    $name = $route -replace '^/(?:api|login)/', ''

    $reqType = "ReqPacket_$name"
    $resType = "ResPacket_$name"
    if (-not $packetClassNames.Contains($reqType) -or -not $packetClassNames.Contains($resType)) {
        $missing += [pscustomobject]@{ Route = $route; Name = $name; Reason = "$reqType/$resType not found under /packets" }
        continue
    }

    $static += [pscustomobject]@{ Route = $route; Name = $name }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// <auto-generated by tools/extract-static-routes.ps1 - do not edit by hand>")
[void]$sb.AppendLine("// Stateless endpoints: Rust handler used static_response and never touched")
[void]$sb.AppendLine("// UserRepository. Stateful endpoints are handled in cycles 3 and 4.")
[void]$sb.AppendLine("// MISSING lines are routes classified stateless whose ReqPacket_/ResPacket_ pair")
[void]$sb.AppendLine("// does not exist under /packets (route name and client packet name have drifted).")
[void]$sb.AppendLine("// Do not invent the type; these are cycle 3 items. Re-running the generator")
[void]$sb.AppendLine("// reproduces the same comment-outs.")
[void]$sb.AppendLine("using Microsoft.AspNetCore.Routing;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("public static class StaticRoutes")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    public static IEndpointRouteBuilder MapStaticPackets(this IEndpointRouteBuilder app)")
[void]$sb.AppendLine("    {")
foreach ($r in ($static | Sort-Object Name)) {
    [void]$sb.AppendLine("        app.MapPacket<ReqPacket_$($r.Name), ResPacket_$($r.Name)>(`"$($r.Route)`");")
}
foreach ($r in ($missing | Sort-Object Name)) {
    [void]$sb.AppendLine("        // MISSING: $($r.Route) - $($r.Reason)")
}
[void]$sb.AppendLine("        return app;")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    public static int RegisteredCount => $($static.Count);")
[void]$sb.AppendLine("}")

Set-Content -Path $OutFile -Value $sb.ToString() -Encoding utf8

Write-Output "Static routes generated: $($static.Count)"
Write-Output "Skipped (stateful or unresolved): $($skipped.Count)"
$skipped | ForEach-Object { Write-Output "  - $_" }
Write-Output "Missing packet types (commented out): $($missing.Count)"
$missing | ForEach-Object { Write-Output "  - $($_.Route): $($_.Reason)" }
