# Extracts packet ID constants from the Rust server into a C# lookup.
# Source of truth: models/src/packets.rs, `impl HasPacketId for ResponseResultApi<Name>`.
# Re-run only when the Rust source changes; output is committed.

param(
    [string]$RustPacketsFile = "C:\Users\Limi\Desktop\Projects\lethe-server\models\src\packets.rs",
    [string]$OutFile = "$PSScriptRoot\..\src\OpenLethe.Server\PacketIds.g.cs"
)

$ErrorActionPreference = "Stop"
$text = Get-Content $RustPacketsFile -Raw

# The brief's ResponseResultApi-only pattern finds 133/153 impls: 20 more use
# other module prefixes (ResponseResultLog*, ResponseResultIap*, ResponseResultLogin*),
# matching the log_/iap_/login_ (and api_) filename prefixes under /packets. "Login"
# must be tried before "Log" in the alternation or it wrongly eats "Log" out of
# "LoginSignInAsGuest" and leaves "inSignInAsGuest" as the name.
$pattern = 'impl\s+HasPacketId\s+for\s+ResponseResult(?:Login|Log|Iap|Api)(?<name>\w+)\s*\{\s*fn\s+packet_id\(\)\s*->\s*i64\s*\{\s*(?<id>-?\d+)'
$matches = [regex]::Matches($text, $pattern)

if ($matches.Count -eq 0) { throw "No packet IDs matched - check the regex against packets.rs" }

$entries = @{}
foreach ($m in $matches) {
    $entries[$m.Groups['name'].Value] = [long]$m.Groups['id'].Value
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// <auto-generated by tools/extract-packet-ids.ps1 - do not edit by hand>")
[void]$sb.AppendLine("// Source: lethe-server/models/src/packets.rs (impl HasPacketId).")
[void]$sb.AppendLine("// Keys are Rust response names with the ResponseResultApi prefix stripped,")
[void]$sb.AppendLine("// matching C# ResPacket_<Key>.")
[void]$sb.AppendLine("using System.Collections.Generic;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("public static class PacketIds")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    private static readonly Dictionary<string, long> Map = new()")
[void]$sb.AppendLine("    {")
foreach ($k in ($entries.Keys | Sort-Object)) {
    [void]$sb.AppendLine("        [`"$k`"] = $($entries[$k]),")
}
[void]$sb.AppendLine("    };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    public static int Count => Map.Count;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    public static bool TryGet(string responseTypeName, out long id)")
[void]$sb.AppendLine("        => Map.TryGetValue(responseTypeName, out id);")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    public static long For(string responseTypeName)")
[void]$sb.AppendLine("        => Map.TryGetValue(responseTypeName, out var id)")
[void]$sb.AppendLine("            ? id")
[void]$sb.AppendLine("            : throw new KeyNotFoundException(")
[void]$sb.AppendLine("                `$`"No packet ID for '{responseTypeName}'. Re-run tools/extract-packet-ids.ps1.`");")
[void]$sb.AppendLine("}")

New-Item -ItemType Directory -Force (Split-Path $OutFile) | Out-Null
Set-Content -Path $OutFile -Value $sb.ToString() -Encoding utf8

Write-Output "Wrote $($entries.Count) packet IDs to $OutFile"
